import React, { useState } from 'react';

/**
 * This is a placeholder component.
 * Replace the contents of this file with the React component
 * generated by your LLM.
 * * Make sure the component is the default export.
 */
function App() {
  const [count, setCount] = useState(0)

  return (
    <div style={{ fontFamily: 'sans-serif', textAlign: 'center', marginTop: '50px' }}>
      <h1>Gemini React Boilerplate</h1>
      <p>Replace this component with your generated code in <code>src/App.jsx</code>.</p>
      <div style={{ marginTop: '20px' }}>
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p style={{ marginTop: '10px' }}>
          Edit <code>src/App.jsx</code> and save to test HMR (Hot Module Replacement).
        </p>
      </div>
    </div>
  )
}

export default App

